// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Configuration par défaut pour les applications Firebase.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions non configuré pour windows - '
          'vous devez reconfigurer FlutterFire CLI',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions non configuré pour windows - '
          'vous devez reconfigurer FlutterFire CLI',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions non configuré pour windows - '
          'vous devez reconfigurer FlutterFire CLI',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions non configuré pour windows - '
          'vous devez reconfigurer FlutterFire CLI',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions non configuré pour linux - '
          'vous devez reconfigurer FlutterFire CLI',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions non configuré pour cette plateforme - '
          'vous devez reconfigurer FlutterFire CLI',
        );
    }
  }

  // Configuration Firebase pour l'application web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDZ-5IDDZH6JAwwLAVKLoTgopdF7EfixoI",
    authDomain: "quizzed-base.firebaseapp.com",
    databaseURL:
        "https://quizzed-base-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "quizzed-base",
    storageBucket: "quizzed-base.firebasestorage.app",
    messagingSenderId: "290804717986",
    appId: "1:290804717986:web:e5b0b7e845cb51ee3ffafb",
    measurementId: "G-VKXENK378H",
  );
}
